name: Test and Deploy

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check
        run: pnpm run check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: build
        env:
          BASE_PATH: '${{ steps.pages.outputs.base_path }}'
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'build/'

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
